java_library(
  name = 'parsing',
  srcs = glob(['*.java']),
  deps = [
    ':annotations',
    '//third-party:guava',
    '//third-party:lang3',
  ],
  visibility = ['//...'],
)

java_library(
  name = 'annotations',
  srcs = glob(['annotations/*.java']),
  visibility = ['//...'],
)