java_library(
  name = 'yuck',
  srcs = glob(['*.java']),
  deps = [
    '//lib:guava',
    '//lib:args4j',
    '//lib:lang3',
    '//lib:hamcrest',
    '//lib:jflex',
  ],
)

java_binary(
  name = 'yuckc',
  main_class = 'com.yuck.Yuckc',
  deps = [
    ':yuck',
  ]
)