java_library(
  name = 'yuck',
  srcs = glob(['*.java']),
  deps = [
    '//third-party:guava',
    '//third-party:args4j',
    '//third-party:lang3',
    '//third-party:hamcrest',
    '//third-party:jflex',
  ],
)

java_binary(
  name = 'yuckc',
  main_class = 'com.yuck.Yuckc',
  deps = [
    ':yuck',
  ]
)