java_library(
  name = 'interpreter',
  srcs = glob(['*.java']),
  deps = [
    '//java/com/yuck/ycode:ycode',
    '//third-party:guava',
    '//third-party:lang3',
    '//third-party:jflex',
  ],
  visibility = ['//...'],
)