java_library(
  name = 'interpreter',
  srcs = glob(['*.java']),
  deps = [
    '//java/com/yuck/ycode:ycode',
    '//java/com/yuck/compilation:compilation',
    '//third-party:guava',
    '//third-party:lang3',
    '//third-party:jflex',
    '//third-party:gson',
  ],
  visibility = ['//...'],
)